### PR TITLE
BE005: Endpoint

### PR DESCRIPTION
**Pull request by LiamStander**

### CODE REVIEW

**Comment by LiamStander** [comment]
@EtienneHoffman kan jy sien idk what im doing lol. Lyk dit okay? Sal met postman test, wil net eers comments kry en gaan paar goed moet verander anyway as die db verander. Of doen ek dit verkeerd?

**Comment by EtienneHoffman** [comment]
@LiamStander Ek sien dit ja, laat ek check

**Review by EtienneHoffman — CHANGES_REQUESTED** [review]
This is not the right place to do SQ. I added new methods in my code to allow you to pass in the field name. Please wait for thsoe changes.

**Comment by LiamStander** [comment]
Is this better? @EtienneHoffman

**Review by EtienneHoffman — APPROVED** [review]

**Pull request merged**
